# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aWOcdIhrXa4kwZaA54BrV-fS1baTLoUG
"""

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier

!wget -O drug200.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/drug200.csv

df = pd.read_csv('drug200.csv')
df.size
df.head()

x = df[['Age','Sex','BP','Cholesterol','Na_to_K']].values
x[0:5]

from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
x[:,1] = le_sex.transform(x[:,1])

le_bp = preprocessing.LabelEncoder()
le_bp.fit(['LOW','NORMAL','HIGH'])
x[:,2] = le_bp.transform(x[:,2])

le_chol = preprocessing.LabelEncoder()
le_chol.fit(['NORMAL','HIGH'])
x[:,3] = le_chol.transform(x[:,3])

y = df[['Drug']]
y.head()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

dectree = DecisionTreeClassifier(criterion = 'entropy',max_depth = 4)
dectree

dectree.fit(x_train,y_train)

pred = dectree.predict(x_test)

from sklearn import metrics
import matplotlib.pyplot as plt

print("accuracy: ",metrics.accuracy_score(pred,y_test))

# Commented out IPython magic to ensure Python compatibility.
from sklearn.externals.six import StringIO
import pydotplus
import matplotlib.image as mpimg
from sklearn import tree
# %matplotlib inline

dot_data = StringIO()
filename = "drugtree.png"
featureNames = df.columns[0:5]
targetNames = df["Drug"].unique().tolist()
out=tree.export_graphviz(dectree,feature_names=featureNames, out_file=dot_data, class_names= np.unique(y_train), filled=True,  special_characters=True,rotate=False)  
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png(filename)
img = mpimg.imread(filename)
plt.figure(figsize=(100, 200))
plt.imshow(img,interpolation='nearest')